///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace JenkinsDemo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the JenkinsDemoRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("2dad6324-194b-4a90-8b88-9fe94e017c11")]
    public partial class JenkinsDemoRepository : RepoGenBaseFolder
    {
        static JenkinsDemoRepository instance = new JenkinsDemoRepository();
        JenkinsDemoRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the JenkinsDemoRepository element repository.
        /// </summary>
        [RepositoryFolder("2dad6324-194b-4a90-8b88-9fe94e017c11")]
        public static JenkinsDemoRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public JenkinsDemoRepository() 
            : base("JenkinsDemoRepository", "/", null, 0, false, "2dad6324-194b-4a90-8b88-9fe94e017c11", ".\\RepositoryImages\\JenkinsDemoRepository2dad6324.rximgres")
        {
            _applicationundertest = new JenkinsDemoRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("2dad6324-194b-4a90-8b88-9fe94e017c11")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("90ab8465-5d2f-4ab3-9802-b93c85317993")]
        public virtual JenkinsDemoRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class JenkinsDemoRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("90ab8465-5d2f-4ab3-9802-b93c85317993")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _ranorexhelpcenterInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='support.ranorex.com']", parentFolder, 30000, null, false, "90ab8465-5d2f-4ab3-9802-b93c85317993", "")
            {
                _ranorexhelpcenterInfo = new RepoItemInfo(this, "RanorexHelpCenter", "?/?/main/div/div/section[1]/h1[@innertext='Ranorex Help Center']", ".//h1[@innertext='Ranorex Help Center']", 30000, null, "5491d3cd-9f67-453e-a41e-dbef4fe1a1e4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("90ab8465-5d2f-4ab3-9802-b93c85317993")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("90ab8465-5d2f-4ab3-9802-b93c85317993")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RanorexHelpCenter item.
            /// </summary>
            [RepositoryItem("5491d3cd-9f67-453e-a41e-dbef4fe1a1e4")]
            public virtual Ranorex.H1Tag RanorexHelpCenter
            {
                get
                {
                    return _ranorexhelpcenterInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The RanorexHelpCenter item info.
            /// </summary>
            [RepositoryItemInfo("5491d3cd-9f67-453e-a41e-dbef4fe1a1e4")]
            public virtual RepoItemInfo RanorexHelpCenterInfo
            {
                get
                {
                    return _ranorexhelpcenterInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
