///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace JenkinsDemo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the JenkinsDemoRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("a7c3fd7c-43df-408f-b751-a97ae4fd0d8b")]
    public partial class JenkinsDemoRepository : RepoGenBaseFolder
    {
        static JenkinsDemoRepository instance = new JenkinsDemoRepository();
        JenkinsDemoRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the JenkinsDemoRepository element repository.
        /// </summary>
        [RepositoryFolder("a7c3fd7c-43df-408f-b751-a97ae4fd0d8b")]
        public static JenkinsDemoRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public JenkinsDemoRepository() 
            : base("JenkinsDemoRepository", "/", null, 0, false, "a7c3fd7c-43df-408f-b751-a97ae4fd0d8b", ".\\RepositoryImages\\JenkinsDemoRepositorya7c3fd7c.rximgres")
        {
            _applicationundertest = new JenkinsDemoRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("a7c3fd7c-43df-408f-b751-a97ae4fd0d8b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("6c180948-0794-4bb6-8f59-571e900e0f3c")]
        public virtual JenkinsDemoRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class JenkinsDemoRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("6c180948-0794-4bb6-8f59-571e900e0f3c")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _ranorexlogoInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "6c180948-0794-4bb6-8f59-571e900e0f3c", "")
            {
                _ranorexlogoInfo = new RepoItemInfo(this, "RanorexLogo", "?/?/header/?/?/a[@href='https://www.ranorex.com/']/img[@alt='Ranorex Logo']", ".//img[@alt='Ranorex Logo']", 30000, null, "abf55897-d57a-4c66-985b-8420dd89f2fe");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6c180948-0794-4bb6-8f59-571e900e0f3c")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6c180948-0794-4bb6-8f59-571e900e0f3c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RanorexLogo item.
            /// </summary>
            [RepositoryItem("abf55897-d57a-4c66-985b-8420dd89f2fe")]
            public virtual Ranorex.ImgTag RanorexLogo
            {
                get
                {
                    return _ranorexlogoInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The RanorexLogo item info.
            /// </summary>
            [RepositoryItemInfo("abf55897-d57a-4c66-985b-8420dd89f2fe")]
            public virtual RepoItemInfo RanorexLogoInfo
            {
                get
                {
                    return _ranorexlogoInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
